services:
    api: &api
        build:
            context: .
            dockerfile: ./docker/production/django/Dockerfile
        image: afriauth_web_image
        container_name: afriauth_web_container
        volumes:
            - ./staticfiles:/app/staticfiles
        ports:
            - "8000:8000"
        env_file:
            - .envs/.production/.django
            - .envs/.production/.postgres
        networks:
            - cvms_docker_network

networks:
    cvms_docker_network:
        external: true
