on:
  push:
    branches:
      - dev2
  # pull_request:
  #   branches:
  #     - testing

name: Deploy backend-end service
jobs:
  deploy:
    name: Deploy to Test Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Build & Push Django Backend to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "./docker/production/dev/Dockerfile"
          IMAGE_NAME: "afripoint/cvms_django_admin_image"
          LATEST: "true"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_TEST_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /root/onenaira/onenaira_server_configuration
            git checkout main
            git reset --hard HEAD
            git pull origin main
            docker stack deploy -c /root/onenaira/onenaira_server_configuration/docker-compose.yml onenaira 

          
